#!/bin/bash

echo ""
echo "========================================"
echo "  Starting Corvin Demo"
echo "========================================"
echo ""
echo "Open 4 terminals and run:"
echo ""
echo "  Terminal 1:  debug"
echo "               (Opens the Corvin chat UI)"
echo ""
echo "  Terminal 2:  cd orders-service && debug npm run dev"
echo ""
echo "  Terminal 3:  cd checkout-service && debug npm run dev"
echo ""
echo "  Terminal 4:  npm run demo:bug1"
echo ""
echo "Wait for 'Connected to Corvin' messages in terminals 2 & 3."
echo ""
echo "Then ask Corvin in Terminal 1:"
echo "  \"Checkout is failing with fullName validation error\""
echo ""
echo "========================================"
echo ""
